# Generated by Django 2.2.3 on 2019-08-25 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('header_image', models.ImageField(blank=True, default='no-img.gif', upload_to='')),
                ('short', models.TextField()),
                ('text', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=512)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.Work')),
                ('volunteer_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.Volunteer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
