# Generated by Django 2.2.3 on 2019-07-30 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('header_image', models.ImageField(blank=True, default='static/uploads/no-img.gif', upload_to='static/uploads/')),
                ('short', models.TextField()),
                ('text', models.TextField()),
                ('technologies', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
