# Generated by Django 2.2.3 on 2019-07-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190730_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='header_image',
            field=models.ImageField(blank=True, default='no-img.gif', upload_to=''),
        ),
    ]
