# Generated by Django 2.2.3 on 2019-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190730_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
