# Generated by Django 2.2.3 on 2019-08-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basics',
            options={},
        ),
    ]
