# Generated by Django 2.2.3 on 2019-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190805_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
