# Generated by Django 2.2.3 on 2019-08-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190825_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basics',
            options={'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-end_date', '-start_date'], 'verbose_name': 'Volunteer Work', 'verbose_name_plural': 'Volunteer Work'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-end_date', '-start_date'], 'verbose_name_plural': 'Work'},
        ),
    ]
