# Generated by Django 2.2.3 on 2019-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_personalinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='gitlab',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='itchio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='medium',
            field=models.URLField(blank=True),
        ),
    ]
