# Generated by Django 2.2.3 on 2019-09-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20190903_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skillset',
        ),
        migrations.DeleteModel(
            name='Skillset',
        ),
    ]
