# Generated by Django 2.2.3 on 2019-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20190807_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
