# Generated by Django 2.2.3 on 2019-09-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20190903_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-start_date', '-end_date'], 'verbose_name': 'Volunteer Work', 'verbose_name_plural': 'Volunteer Work'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-start_date', '-end_date'], 'verbose_name_plural': 'Work'},
        ),
    ]
