# Generated by Django 2.2.3 on 2019-08-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_skill_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.Job')),
            ],
            options={
                'db_table': 'volunteer_jobs',
                'ordering': ['-completion_date', '-start_date'],
            },
            bases=('resume.job',),
        ),
    ]
