# Generated by Django 2.2.3 on 2019-08-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_volunteerjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('reference_text', models.TextField()),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_name', models.CharField(max_length=30)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='github',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='gitlab',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='itchio',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='twitter',
        ),
    ]
