# Generated by Django 2.2.3 on 2019-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20190824_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
