# Generated by Django 2.2.3 on 2019-08-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20190824_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='study_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VolunteerAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.VolunteerJob')),
            ],
            options={
                'db_table': 'volunteer_accomplishments',
                'ordering': ['order'],
            },
        ),
    ]
