# Generated by Django 2.2.3 on 2019-08-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20190825_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='fluency',
            field=models.CharField(default='Native', max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SkillKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Skill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterestKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Interest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Education')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
