# Generated by Django 2.2.3 on 2019-08-25 11:43

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20190825_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='job',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Job'),
        ),
        migrations.AlterField(
            model_name='course',
            name='education',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Education'),
        ),
        migrations.AlterField(
            model_name='interestkeyword',
            name='interest',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Interest'),
        ),
        migrations.AlterField(
            model_name='skillkeyword',
            name='skill',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Skill'),
        ),
        migrations.AlterField(
            model_name='volunteeraccomplishment',
            name='job',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.VolunteerJob'),
        ),
    ]
