# Generated by Django 2.2.3 on 2019-08-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20190825_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='label',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
